baseurl = "https://leadinchina.com/"
title = "Open to 1.4 Billion People"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
googleAnalytics = "UA-67874206-3"

[params]
  description = "Your Personalized Business Lead To China"
  logo = "fa-star"
  copyright = "leadinchina.com"